//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class crudUSuarioEntities : DbContext
    {
        public crudUSuarioEntities()
            : base("name=crudUSuarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<usuario> usuario { get; set; }
    
        public virtual int actualizarUsuario(Nullable<int> p_id, string p_nombre, Nullable<System.DateTime> p_fechaNacimiento, string p_sexo)
        {
            var p_idParameter = p_id.HasValue ?
                new ObjectParameter("p_id", p_id) :
                new ObjectParameter("p_id", typeof(int));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            var p_fechaNacimientoParameter = p_fechaNacimiento.HasValue ?
                new ObjectParameter("p_fechaNacimiento", p_fechaNacimiento) :
                new ObjectParameter("p_fechaNacimiento", typeof(System.DateTime));
    
            var p_sexoParameter = p_sexo != null ?
                new ObjectParameter("p_sexo", p_sexo) :
                new ObjectParameter("p_sexo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizarUsuario", p_idParameter, p_nombreParameter, p_fechaNacimientoParameter, p_sexoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> crearUsuario(string p_nombre, Nullable<System.DateTime> p_fechaNacimiento, string p_sexo)
        {
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            var p_fechaNacimientoParameter = p_fechaNacimiento.HasValue ?
                new ObjectParameter("p_fechaNacimiento", p_fechaNacimiento) :
                new ObjectParameter("p_fechaNacimiento", typeof(System.DateTime));
    
            var p_sexoParameter = p_sexo != null ?
                new ObjectParameter("p_sexo", p_sexo) :
                new ObjectParameter("p_sexo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("crearUsuario", p_nombreParameter, p_fechaNacimientoParameter, p_sexoParameter);
        }
    
        public virtual int eliminarUsuario(Nullable<int> p_id)
        {
            var p_idParameter = p_id.HasValue ?
                new ObjectParameter("p_id", p_id) :
                new ObjectParameter("p_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("eliminarUsuario", p_idParameter);
        }
    
        public virtual int leerUsuarios(string p_filtro, string p_orden)
        {
            var p_filtroParameter = p_filtro != null ?
                new ObjectParameter("p_filtro", p_filtro) :
                new ObjectParameter("p_filtro", typeof(string));
    
            var p_ordenParameter = p_orden != null ?
                new ObjectParameter("p_orden", p_orden) :
                new ObjectParameter("p_orden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("leerUsuarios", p_filtroParameter, p_ordenParameter);
        }
    }
}
