//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaPresentacion.UsuarioReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usuario", Namespace="http://schemas.datacontract.org/2004/07/capaDatos")]
    [System.SerializableAttribute()]
    public partial class usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                if ((this.fechaNacimientoField.Equals(value) != true)) {
                    this.fechaNacimientoField = value;
                    this.RaisePropertyChanged("fechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioReference.IUsuario")]
    public interface IUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Consultar", ReplyAction="http://tempuri.org/IUsuario/ConsultarResponse")]
        capaPresentacion.UsuarioReference.usuario[] Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Consultar", ReplyAction="http://tempuri.org/IUsuario/ConsultarResponse")]
        System.Threading.Tasks.Task<capaPresentacion.UsuarioReference.usuario[]> ConsultarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Agregar", ReplyAction="http://tempuri.org/IUsuario/AgregarResponse")]
        int Agregar(string nombre, string fechaNacimiento, string sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Agregar", ReplyAction="http://tempuri.org/IUsuario/AgregarResponse")]
        System.Threading.Tasks.Task<int> AgregarAsync(string nombre, string fechaNacimiento, string sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Modificar", ReplyAction="http://tempuri.org/IUsuario/ModificarResponse")]
        int Modificar(string nombre, string fechaNacimiento, string sexo, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Modificar", ReplyAction="http://tempuri.org/IUsuario/ModificarResponse")]
        System.Threading.Tasks.Task<int> ModificarAsync(string nombre, string fechaNacimiento, string sexo, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Eliminar", ReplyAction="http://tempuri.org/IUsuario/EliminarResponse")]
        int Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Eliminar", ReplyAction="http://tempuri.org/IUsuario/EliminarResponse")]
        System.Threading.Tasks.Task<int> EliminarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Leer", ReplyAction="http://tempuri.org/IUsuario/LeerResponse")]
        capaPresentacion.UsuarioReference.usuario Leer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Leer", ReplyAction="http://tempuri.org/IUsuario/LeerResponse")]
        System.Threading.Tasks.Task<capaPresentacion.UsuarioReference.usuario> LeerAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioChannel : capaPresentacion.UsuarioReference.IUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioClient : System.ServiceModel.ClientBase<capaPresentacion.UsuarioReference.IUsuario>, capaPresentacion.UsuarioReference.IUsuario {
        
        public UsuarioClient() {
        }
        
        public UsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public capaPresentacion.UsuarioReference.usuario[] Consultar() {
            return base.Channel.Consultar();
        }
        
        public System.Threading.Tasks.Task<capaPresentacion.UsuarioReference.usuario[]> ConsultarAsync() {
            return base.Channel.ConsultarAsync();
        }
        
        public int Agregar(string nombre, string fechaNacimiento, string sexo) {
            return base.Channel.Agregar(nombre, fechaNacimiento, sexo);
        }
        
        public System.Threading.Tasks.Task<int> AgregarAsync(string nombre, string fechaNacimiento, string sexo) {
            return base.Channel.AgregarAsync(nombre, fechaNacimiento, sexo);
        }
        
        public int Modificar(string nombre, string fechaNacimiento, string sexo, int id) {
            return base.Channel.Modificar(nombre, fechaNacimiento, sexo, id);
        }
        
        public System.Threading.Tasks.Task<int> ModificarAsync(string nombre, string fechaNacimiento, string sexo, int id) {
            return base.Channel.ModificarAsync(nombre, fechaNacimiento, sexo, id);
        }
        
        public int Eliminar(int id) {
            return base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task<int> EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
        
        public capaPresentacion.UsuarioReference.usuario Leer(int id) {
            return base.Channel.Leer(id);
        }
        
        public System.Threading.Tasks.Task<capaPresentacion.UsuarioReference.usuario> LeerAsync(int id) {
            return base.Channel.LeerAsync(id);
        }
    }
}
